//mod print;
//mod var;
//mod types;
//mod strings;
//mod tuples;
//mod arrays;
//mod vectors;
//mod conditionals;
//mod loops;
//mod functions;
//mod pointer_ref;
//mod structs;
//mod enums;
//mod cli;
//mod types_example;
//mod loop_example;
//mod function_example;
//mod array_example;
mod impl_example;

fn main() {
    //print::run();
    //var::run();
    //types::run();
    //strings::run();
    //tuples::run();
    //arrays::run();
    //vectors::run();
    //conditionals::run();
    //loops::run();
    //functions::run();
    //pointer_ref::run();
    //structs::run();
    //enums::run();
    //cli::run();
    //types_example::run();
    //loop_example::run();
    //function_example::run();
    //array_example::run();
    impl_example::run();
}
